/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.0.0.24.1
    Soft IP Version: 1.2.0
    2021 11 21 17:24:39
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module stack64 (clk_i, rst_i, clk_en_i, wr_en_i, wr_data_i, addr_i, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_i;
    input  clk_en_i;
    input  wr_en_i;
    input  [31:0]  wr_data_i;
    input  [5:0]  addr_i;
    output  [31:0]  rd_data_o;
endmodule